### ISSUE TITLE
can rlottie support width and height Scaling at not the same scale,I edit this function to do this,but I dont know is there any problems here.

### ISSUE THREAD

**Issue by fantasyARM** [Samsung/rlottie#106]
bool LOTCompItem::update(int frameNo)
{
    // check if cached frame is same as requested frame.
    if (!mUpdateViewBox && (mCurFrameNo == frameNo)) return false;

    /*
     * if viewbox dosen't scale exactly to the viewport
     * we scale the viewbox keeping AspectRatioPreserved and then align the
     * viewbox to the viewport using AlignCenter rule.
     */
    VSize viewPort = mViewSize;
    VSize viewBox = mCompData->size();

    float sx = float(viewPort.width()) / viewBox.width();
    float sy = float(viewPort.height()) / viewBox.height();
    float scale = fmin(sx, sy);
    float tx = (viewPort.width() - viewBox.width() * sx) * 0.5;
    float ty = (viewPort.height() - viewBox.height() * sy) * 0.5;

    VMatrix m;
    m.translate(tx, ty).scale(sx, sy);
    mRootLayer->update(frameNo, m, 1.0);

    mCurFrameNo = frameNo;
    mUpdateViewBox = false;
    return true;
}

**Comment by smohantty** [comment]
rlottie keeps the aspect ratio of the resource file which applying the scale.
Ex: if the original resource size if (100, 100) 1:1
      And user requests a rendering area of (200 X 300) , the maximum size can be created while keeping the aspect ratio is (200, 200) and then we just align it to center.

If i understood correctly you want to fill the whole rendering area (without keeping the aspect ratio of original resource).
If its a valid use case then we may add that feature to rlottie.

**Comment by fantasyARM** [comment]
yes,this is what I want. Ex:original size (500,200),I want fill (1280,720) the whole rendering area.

**Comment by fantasyARM** [comment]
but I want to know:
bool LOTCompItem::update(int frameNo)
{
// check if cached frame is same as requested frame.
if (!mUpdateViewBox && (mCurFrameNo == frameNo)) return false;

/*
 * if viewbox dosen't scale exactly to the viewport
 * we scale the viewbox keeping AspectRatioPreserved and then align the
 * viewbox to the viewport using AlignCenter rule.
 */
VSize viewPort = mViewSize;
VSize viewBox = mCompData->size();

float sx = float(viewPort.width()) / viewBox.width();
float sy = float(viewPort.height()) / viewBox.height();
float scale = fmin(sx, sy);
float tx = (viewPort.width() - viewBox.width() * sx) * 0.5;
float ty = (viewPort.height() - viewBox.height() * sy) * 0.5;

VMatrix m;
m.translate(tx, ty).scale(sx, sy);
mRootLayer->update(frameNo, m, 1.0);

mCurFrameNo = frameNo;
mUpdateViewBox = false;
return true;
}   ---------------------------------------- is this code can always runs ok?I havent read all the rlootie code,yet.

**Comment by fantasyARM** [comment]
by the way,I will add rlottie to ffmpeg filters.

**Comment by smohantty** [comment]
Yes this code runs always before rendering .. thats how we can update the root matrix according to the requested size.
