### ISSUE TITLE
can rlottie update to the newest version.

### ISSUE THREAD

**Issue by fantasyARM** [Samsung/rlottie#128]
we found that,the new designed lottie, can not rend pictures.can you fix this? I can send you my json documents.

**Comment by smohantty** [comment]
Yaa sure .. send me the resource that has problem ... if its difficult to debug with that .. i amy ask you to send the AEP file.

Thanks
Subhransu

**Comment by fantasyARM** [comment]
can you leave your email.I will send  to you.

**Comment by smohantty** [comment]
smohantty@gmail.com

**Comment by smohantty** [comment]
@fantasyARM , I checked your resources and found that most of them are using Text Layer.
unfortunately rlottie dosen't  support Text layer yet.

You can create a Shape layer from Text by right click on Text layer --> 'create' -> 'create shapes from text' option.

Let me know if that solves your issue .

Thanks
Subhransu
