### ISSUE TITLE
cmake make fail on Mac

### ISSUE THREAD

**Issue by yoer** [Samsung/rlottie#130]
make -j 2

Scanning dependencies of target rlottie-image-loader
Scanning dependencies of target rlottie
[  2%] Building CXX object src/vector/stb/CMakeFiles/rlottie-image-loader.dir/stb_image.cpp.o
[  5%] Building CXX object CMakeFiles/rlottie.dir/src/vector/freetype/v_ft_math.cpp.o
[  8%] Building CXX object CMakeFiles/rlottie.dir/src/vector/freetype/v_ft_raster.cpp.o
[ 10%] Linking CXX shared library librlottie-image-loader.dylib
[ 10%] Built target rlottie-image-loader
[ 13%] Building CXX object CMakeFiles/rlottie.dir/src/vector/freetype/v_ft_stroker.cpp.o
[ 16%] Building CXX object CMakeFiles/rlottie.dir/src/vector/pixman/vregion.cpp.o
[ 18%] Building CXX object CMakeFiles/rlottie.dir/src/vector/vrect.cpp.o
[ 21%] Building CXX object CMakeFiles/rlottie.dir/src/vector/vdasher.cpp.o
[ 24%] Building CXX object CMakeFiles/rlottie.dir/src/vector/vbrush.cpp.o
[ 27%] Building CXX object CMakeFiles/rlottie.dir/src/vector/vbitmap.cpp.o
[ 29%] Building CXX object CMakeFiles/rlottie.dir/src/vector/vpainter.cpp.o
[ 32%] Building CXX object CMakeFiles/rlottie.dir/src/vector/vcompositionfunctions.cpp.o
[ 35%] Building CXX object CMakeFiles/rlottie.dir/src/vector/vdrawhelper.cpp.o
[ 37%] Building CXX object CMakeFiles/rlottie.dir/src/vector/vdrawhelper_sse2.cpp.o
[ 40%] Building CXX object CMakeFiles/rlottie.dir/src/vector/vdrawhelper_neon.cpp.o
[ 43%] Building CXX object CMakeFiles/rlottie.dir/src/vector/vrle.cpp.o
[ 45%] Building CXX object CMakeFiles/rlottie.dir/src/vector/vpath.cpp.o
[ 48%] Building CXX object CMakeFiles/rlottie.dir/src/vector/vpathmesure.cpp.o
[ 51%] Building CXX object CMakeFiles/rlottie.dir/src/vector/vmatrix.cpp.o
[ 54%] Building CXX object CMakeFiles/rlottie.dir/src/vector/velapsedtimer.cpp.o
[ 56%] Building CXX object CMakeFiles/rlottie.dir/src/vector/vdebug.cpp.o
[ 59%] Building CXX object CMakeFiles/rlottie.dir/src/vector/vinterpolator.cpp.o
[ 62%] Building CXX object CMakeFiles/rlottie.dir/src/vector/vbezier.cpp.o
[ 64%] Building CXX object CMakeFiles/rlottie.dir/src/vector/vraster.cpp.o
[ 67%] Building CXX object CMakeFiles/rlottie.dir/src/vector/vdrawable.cpp.o
[ 70%] Building CXX object CMakeFiles/rlottie.dir/src/vector/vimageloader.cpp.o
[ 72%] Building CXX object CMakeFiles/rlottie.dir/src/lottie/lottieitem.cpp.o
[ 75%] Building CXX object CMakeFiles/rlottie.dir/src/lottie/lottieloader.cpp.o
[ 78%] Building CXX object CMakeFiles/rlottie.dir/src/lottie/lottiemodel.cpp.o
[ 81%] Building CXX object CMakeFiles/rlottie.dir/src/lottie/lottieproxymodel.cpp.o
[ 83%] Building CXX object CMakeFiles/rlottie.dir/src/lottie/lottieparser.cpp.o
[ 86%] Building CXX object CMakeFiles/rlottie.dir/src/lottie/lottieanimation.cpp.o
[ 89%] Building CXX object CMakeFiles/rlottie.dir/src/lottie/lottiekeypath.cpp.o
[ 91%] Building CXX object CMakeFiles/rlottie.dir/src/binding/c/lottieanimation_capi.cpp.o
[ 94%] Linking CXX shared library librlottie.dylib
ld: unknown option: --no-undefined
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [librlottie.0.0.1.dylib] Error 1
make[1]: *** [CMakeFiles/rlottie.dir/all] Error 2
make: *** [all] Error 2

**Comment by smohantty** [comment]
Have added  a patch to fix this issue #131
