### ISSUE TITLE
Memory Leaks

### ISSUE THREAD

**Issue by overtake** [Samsung/rlottie#137]
Hi guys. thanks you for awesome work. I have using rlottie on macos. but it seems have memory leaks.
For example i released everying what connected with lottie but i still see objects in memory leaker. 

See screenshot 

![image](https://user-images.githubusercontent.com/1260850/59604826-9318f700-910d-11e9-8eae-00f979153f2a.png)

**Comment by overtake** [comment]
i'm not sure. but maybe its some cached models?

**Comment by smohantty** [comment]
Yes we cache the model against the resource file. its not a memory leak.
