### ISSUE TITLE
Hidden Elements is visible

### ISSUE THREAD

**Issue by overtake** [Samsung/rlottie#138]
see attached files. Bones is hidden but visible in this player.

![image](https://user-images.githubusercontent.com/1260850/59637634-9684a080-9156-11e9-9bb7-04dae7768c0e.png)

[rlottie-fail.json.zip](https://github.com/Samsung/rlottie/files/3298879/rlottie-fail.json.zip)

**Comment by overtake** [comment]
there is sample of application when this file caused dead lock
[Sample of Telegram.txt](https://github.com/Samsung/rlottie/files/3298959/Sample.of.Telegram.txt)

**Comment by overtake** [comment]
deadlock mostly happens on 21 or 61 frame.

![image](https://user-images.githubusercontent.com/1260850/59639928-d5b5f000-915c-11e9-8346-a4dea1aaa0bc.png)

**Comment by overtake** [comment]
Ok. i solved issue with bones. but i'm not sure about dead-lock

**Comment by overtake** [comment]
So. i think deadlock happens when file has a lot of layers. because now with my fix. 17 layer of 35 is hidden and no deadlock (can't reproduce). but Of course we can return layers visibility and reproduce it

**Comment by smohantty** [comment]
@overtake ,
I have pushed a patch to fix the Hidden layer issue by forcing it as a Null Layer.
As per my understanding if the layer is hidden then it will not take part in the rendering and will only affect(the final transformation of the child layer) if some other layer has set this hidden layer as parent.

If that is the case then creating a Null Layer will do the job.
Am just curious if there is other use case of hidden layer (which can not be achieved using Null Layer) ?

Note: Adding a Shape layer as hidden layer will increase the resource size. 
Thanks
Subhransu

**Comment by overtake** [comment]
Thank you for fixing. issue
