### ISSUE TITLE
cmake error for install command on windows

### ISSUE THREAD

**Issue by yuangu** [Samsung/rlottie#14]
I'm try build it  by cmake on my win10。but it error form this install command of cmake.here is the error infomation. 

![1552620984(1)](https://user-images.githubusercontent.com/1897438/54407044-6670d000-4717-11e9-8a07-0f2dcbefdfeb.jpg)

and the official documents of cmake (https://cmake.org/cmake/help/v3.14/command/install.html) say to us, 

`
 For DLL platforms (all Windows-based systems including Cygwin), the DLL import library is treated as an ARCHIVE target.
 For non- DLL platforms shared libraries are treated as LIBRARY targets.
`
so this cmake code change to  
`IF(WIN32)

install(TARGETS rlottie-image-loader
ARCHIVE DESTINATION ${LIB_INSTALL_DIR}
       )
ELSE(WIN32)
install(TARGETS rlottie-image-loader
        LIBRARY DESTINATION ${LIB_INSTALL_DIR}
       )
ENDIF(WIN32)`

^_^  the last command : `cmake .. -Dexample=true  -DLIB_INSTALL_DIR="D:/out"`  
it's work well

**Comment by hermet** [comment]
@yuangu , Thanks for your feedback, 
What do you think if you contribute the patch for this project?

**Comment by hermet** [comment]
Hopefully, this is fixed by this patch.

commit 9bd4062efbd8a9e435038bff7236d31a7ca1ddaa (HEAD -> master, origin/master, origin/HEAD)
Author: Hermet Park <hermetpark@gmail.com>
Date:   Mon Mar 18 16:34:33 2019 +0900

    cmake: fix cmake error for install command on windows

    For DLL platforms (all Windows-based systems including Cygwin),
    the DLL import library is treated as an ARCHIVE target.

    https://github.com/Samsung/rlottie/issues/14#issue-421341587
