### ISSUE TITLE
Dead lock is here

### ISSUE THREAD

**Issue by overtake** [Samsung/rlottie#141]
So. dead lock still there ;(

![image](https://user-images.githubusercontent.com/1260850/59665345-fe68d480-91b2-11e9-8cd2-6cb30a68c1d6.png)

**Comment by overtake** [comment]
So. weird thing is there. Sometimes this file has artefacts (right eye). Its looks like problem in parsing model because if we relaunch app and try to play again (without cached model) its may be fine or with artefact (doesn't matter creating new player or not)

![image](https://user-images.githubusercontent.com/1260850/59666701-a5e70680-91b5-11e9-9bfd-d6bc1e7a434f.png)

**Comment by smohantty** [comment]
@overtake , I tested by disabling the threading (by commenting LOTTIE_THREAD_SUPPORT in config.h)
but the occasional hang is still there. Yet to figure out on which frame it occurs . looks like the final path calculation after transform resulting some path that freetype raster is unable to process.

If the eye is the problem . could you please create a resource file by disabling all other layer except right eye. and send it to me for further debugging.
or you can send me the AE file if thats ok with you . either one will help.

**Comment by overtake** [comment]
can you reproduce the hang?

**Comment by overtake** [comment]
the another thread always stuck here

![image](https://user-images.githubusercontent.com/1260850/59668412-bf3d8200-91b8-11e9-9298-ef75facd3136.png)

**Comment by smohantty** [comment]
Yes I can reproduce it .. its in the freetype raster code.
just want to know which path causing this.

**Comment by smohantty** [comment]
will wait for the resource file

**Comment by overtake** [comment]
@smohantty  there is a source file
 [bunnyta kiss cutted 2.aep.zip](https://github.com/Samsung/rlottie/files/3300823/bunnyta.kiss.cutted.2.aep.zip)

**Comment by overtake** [comment]
the sticker contains bones (controller) maybe its connected?

**Comment by smohantty** [comment]
@smohantty , am using After Effect CC 2018. the AEP file you provided is created using a newer version.
Could you ask them to save it as CC(18) or lower and send it to me.

Thanks

**Comment by smohantty** [comment]
@overtake , am using After Effect CC 2018. the AEP file you provided is created using a newer version.
Could you ask them to save it as CC(18) or lower and send it to me.

Thanks

**Comment by overtake** [comment]
[bunnyta kiss cutted 2 copy CC (15.x).aep.zip](https://github.com/Samsung/rlottie/files/3300941/bunnyta.kiss.cutted.2.copy.CC.15.x.aep.zip)

**Comment by smohantty** [comment]
@overtake ,
one update ..
in Layer "eyes" -> "blue outline" --> group6 --> path1 uses expression for path animation.
we don't support expression in rlottie. I don't know if that is the problem or something else . need to debug more tomorrow.
FYI , I see usage of "merge path" and expression in the AE file . currently rlottie dosen't support both.

**Comment by overtake** [comment]
Ok, thanks you very much. Waiting updates. More import to explore deadlock and find what the break the calculations.

**Comment by smohantty** [comment]
@overtake ,
I have pushed a fix for the same .. it was silly typo which was causing invalid memory access :(

**Comment by overtake** [comment]
Great to hear it. Thank you for you work!

**Comment by overtake** [comment]
So... About simple typos...

![image](https://user-images.githubusercontent.com/1260850/59746535-6b45a280-9277-11e9-9f3f-b70798fdbbbe.png)

**Comment by overtake** [comment]
Hm how she's right eye not blue. its blue on one frame.
![image](https://user-images.githubusercontent.com/1260850/59746746-cf686680-9277-11e9-9fef-85d7a97a6b03.png)

**Comment by smohantty** [comment]
@overtake ,
Sorry was too much into the dead lock :) .. Have push a patch to take care of the scenario when we transition from 1 shape to other (of different size).

**Comment by overtake** [comment]
i understand, small typos can take such lot of time.  But! Finally fixed! Thank you man! 
Also i'm using your framework in Telegram messenger (macos.telegram.org) for playing animated stickers in chat. and its working fasten than any other frameworks.

**Comment by smohantty** [comment]
@overtake , Wow that's great news :)
Is it already part of the MacOS Telegarm Application.
Would like to check it out :)

**Comment by overtake** [comment]
https://rink.hockeyapp.net/apps/6ed2ac3049e1407387c2f1ffcb74e81f

here you can test a lot stickers it in beta. https://t.me/topanimated channel.

**Comment by smohantty** [comment]
thanks :)

**Comment by hermet** [comment]
@overtake Is it open source code? Could you share me the link? I'd like to see how rlottie is integrated in your project.

**Comment by overtake** [comment]
@hermet is it. but i'm updating code on git after each release.

https://github.com/overtake/TelegramSwift

i just made a new submodule and project for rlottie. For example here how i pulling the frames from library. And for playing i have wrote player which pulling frames in background to samplebuffer

![image](https://user-images.githubusercontent.com/1260850/59835612-453d0280-934a-11e9-98f0-76fbf8c7cdfd.png)
