### ISSUE TITLE
Some glitches ;)

### ISSUE THREAD

**Issue by overtake** [Samsung/rlottie#146]
![image](https://user-images.githubusercontent.com/1260850/59966661-cc8f9f00-951f-11e9-8702-c17959ccd764.png)

[data.json.zip](https://github.com/Samsung/rlottie/files/3317055/data.json.zip)

[Panda kissing heart copy (CC (13)).aep.zip](https://github.com/Samsung/rlottie/files/3317054/Panda.kissing.heart.copy.CC.13.aep.zip)

**Comment by smohantty** [comment]
@overtake,
Looks like its stroke rendering issue (with line join as Miter Join) . This is a known issue in freetype 
stroker which does not handle extreme angle when join style is Miter. will try to fix this issue soon.

In the meanwhile the easiest solution is to change the line join to something other than miter limit.
I changed the Line Join Property of below object(in the attached AEP file).
Pre-Comp 5--> body Outlines 2 -> Stroke 1 ->line Join = Bevel Join. 
which fixed the issue with out any visible side effect.
I would recommend you to ask the designer to change the above property till this issue gets resolved.

**Comment by smohantty** [comment]
Have pushed a patch for the same #149

**Comment by overtake** [comment]
works now. Thanks. ;)

**Comment by smohantty** [comment]
@overtake ,
Just for your information,
If you enable "Skip Default Property" in the BodyMovin Plugin Settings->Advanced(Advanced Export Features) , The Panda.json file size reduced from 240KB to 213KB.
Maybe you can ask the UX to enable that while exporting JSON resource to reduce size(hence json parsing performance).
