### ISSUE TITLE
windows (mingw-w64) : meson fails because of dl not found

### ISSUE THREAD

**Issue by vtorri** [Samsung/rlottie#160]
hello

meson .. --prefix=/opt/rlotti --buildtype=debug --default-library shared

gives

src/vector/meson.build:33:0: ERROR: C++ library 'dl' not found

**Comment by smohantty** [comment]
@vtorri ,
The temporary fix is uncommenting //#define LOTTIE_STATIC_IMAGE_LOADER in src/vector/config.h

I will provide a proper fix for the issue as well as a compiler option to choose image loader to build as static library or as a module .

Thanks
Subhransu

**Comment by vtorri** [comment]
fixed, closing
