### ISSUE TITLE
Never include Windows.h, instead include windows.h

### ISSUE THREAD

**Issue by vtorri** [Samsung/rlottie#161]
in src/vector/vimageloader.cpp, Windows.h is included.

When cross-compilation is done on Unix (case sensitive file system), then the compilation will fail, as windows.h and not Windows.h is provided

**Comment by vtorri** [comment]
i can provide a PR if you want

**Comment by smohantty** [comment]
@vtorri,
That will be great

**Comment by vtorri** [comment]
PR #164
