### ISSUE TITLE
Windows: M_PI undefined

### ISSUE THREAD

**Issue by vtorri** [Samsung/rlottie#166]
On Windows M_PI is defined only if

#define _USE_MATH_DEFINES

is called just before #include <cmath> in src/lottie/lottiemodel.cpp, src/vector/vdasher.cpp, vbezier.cpp and vpath.cpp too. See

https://docs.microsoft.com/fr-fr/cpp/c-runtime-library/math-constants?view=vs-2019

you can, if you want, embed this macro in a #ifdef_WIN32

**Comment by vtorri** [comment]
../src/vector/vline.h:58:30: error: 'atan2f' is not a member of 'std'

**Comment by vtorri** [comment]
more precisely

https://en.cppreference.com/w/cpp/numeric/math/atan2

so std::atan2f is defined in c++11. Do you force c++11 compiler with -std ?

**Comment by smohantty** [comment]
@vtorri ,
Yes rlottie has a hard dependancy of std++14. it works on linux system need to check why it fails on windows . will test it on Monday.

**Comment by smohantty** [comment]
@vtorri ,
have pushed a patch which reverts to using atan2().

**Comment by vtorri** [comment]
fixed, closing, but other errors are still here :)

**Comment by vtorri** [comment]
../src/lottie/lottiemodel.cpp:305:56: error: 'M_PI' was not declared in this scope

**Comment by smohantty** [comment]
@vtorri , I have already pushed a patch for the same.
you can close this issue if its fixed.

**Comment by vtorri** [comment]
seems fixed here, closing
