### ISSUE TITLE
realpath does not exists on Windows

### ISSUE THREAD

**Issue by vtorri** [Samsung/rlottie#170]
../example/lottie2gif.cpp:97:20: error: 'realpath' was not declared in this scope

use _fullpath instead : 

https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/fullpath-wfullpath?view=vs-2019

**Comment by vtorri** [comment]
See PR #176

**Comment by vtorri** [comment]
PR #176 deleted, see PR #178

**Comment by smohantty** [comment]
thanks for the patch :)
