### ISSUE TITLE
commit 8b5851ca52cc7fb07695fce7603471ccbd1c7192 is wrong

### ISSUE THREAD

**Issue by vtorri** [Samsung/rlottie#186]
commit 8b5851ca52cc7fb07695fce7603471ccbd1c7192 must be reverted

Indeed, on Windows, both / and \ are path separators

**Comment by smohantty** [comment]
@vtorri ,
I tested it in windows 10 , with your patch base pointer was always returning null.
with the current patch it gave the correct filename.
if both are valid then need to handle both cases.

**Comment by vtorri** [comment]
hmm, ha, ok
then i was wrong with the test : 

if (base)
{
    base++;
    strrchr(base+1, '\\');
}
else
  base = strrchr(baseName.data(), '\\');

if (!base) return 1;


should be good

**Comment by vtorri** [comment]
you can of course test first \ then in the test /

maybe it will be more efficient

**Comment by vtorri** [comment]
if you agree, i write a PR

**Comment by smohantty** [comment]
@vtorri ,
char *base ;
 if (base = strrchr(baseName.data(), '\\') ||
      base = strrchr(baseName.data(), '/') )
     {
        //do smthing
      }

This should do the job.

Please raise a patch for the same.

**Comment by smohantty** [comment]
@vtorri ,
char *base ;
if (base = strrchr(baseName.data(), '\\') ||
base = strrchr(baseName.data(), '/') )
{
//do smthing
}

This should do the job.

Please raise a patch for the same.

**Comment by vtorri** [comment]
i don't think so :

if the file has the following path :+1: 
c:\foo1/foo2\file

base = strrchr(baseName.data(), ' \ ') : base == file so not NULL
so second strrchr is run : base ==foo2\file

if (base = strrchr(baseName.data(), ' \ ') || base = strrchr(base + 1, '/') )

would be better

**Comment by smohantty** [comment]
@vtorri ,
The 2nd strrchr() will not run because of || operator
as the 1st expression results into true it will execute the body without executing the 2nd part of if expression.

**Comment by smohantty** [comment]
@vtorri 
if base is not null , then 2nd expression will not execute because of || operator.
if thats what you meant.

**Comment by vtorri** [comment]
anyway, what i want to say is that you must run the 2nd strrchr(** '\') from the latest occurence returned by strrchr(**,'/), not from the beginning of the file name

**Comment by vtorri** [comment]
so, with this path : 

c:\foo1\foo2/file

and you test : (base = strrchr(baseName.data(), ' \ ') || base = strrchr(baseName.data(), '/') )

strrchr(baseName.data(), ' \ ') returns a non NULL string : c:\foo1, the second test is not taken into account, but the string is foo2/file

so it's not basename

**Comment by vtorri** [comment]
so for me, the algo is

base = strrchr(baseName.data(), ' \ ') 
if (base) base = strrchr(base +1 , '/')
else  base = strrchr(baseName.data(), '/')

**Comment by smohantty** [comment]
@vtorri , now i got your point.
have raised a patch for the same
#187

**Comment by vtorri** [comment]
why not using http://www.cplusplus.com/reference/string/string/find_last_of/ with "\\/" ? the code could be smaller, no ?

**Comment by smohantty** [comment]
@vtorri ,
yes find_lastof() is the perfect api . thanks for pointing out. :)
have pushed a patch for the same #196

**Comment by smohantty** [comment]
regarding performance .. its a example code so not that important and it removes the hand rolled api
