### ISSUE TITLE
LOT_BUILD is not correctly defined

### ISSUE THREAD

**Issue by vtorri** [Samsung/rlottie#194]
LOT_BUILD should not be defined for the entire project : 

LOT_BUILD  must be defined for the library and NOT the programs.

in addition DLL_EXPORT must be defined only when the shared library is built, though, on Windows, only shared lib should be built

I have a patch for this, i will create a PR

**Comment by smohantty** [comment]
@vtorri , 
     I just used the LOT_BUILD generated by the sample meson project.
   
      LOT_BUILD must be defined for the library and NOT the programs.
           - this part is right, need to be added as a cpp_arg instead of project argument.

   will wait for your PR :)

**Comment by vtorri** [comment]
the other part (DLL_EXPORT) is right too as otherwise __declspec(dllexport) will never be passed to the API....

**Comment by vtorri** [comment]
DLL_EXPORT has been removed, so i guess you have removed the static linking, it's good :)

**Comment by vtorri** [comment]
PR #197
