### ISSUE TITLE
03eb0d21d54c6afa3e94c72097891b32ae25ae51 breaks compilation with MSYS2

### ISSUE THREAD

**Issue by vtorri** [Samsung/rlottie#210]
Dependency threads found: YES
Program cmake found: YES (E:\Documents\programmes_x64\msys2\usr\bin/cmake.EXE)
Program cmake found: YES (E:\Documents\programmes_x64\msys2\usr\bin/cmake.EXE)
error retrieving cmake informations: returnCode=255 stdout= stderr=System is unknown to cmake, create:
Platform/MINGW64_NT-6.1-7601 to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
System is unknown to cmake, create:
Platform/MINGW64_NT-6.1-7601 to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
CMake Error at /usr/share/cmake-3.14.5/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "/mingw64/bin/cc.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/vtorri/gitroot_64/rlottie_vtorri/builddir/__cmake_systeminformation/CMakeFiles/CMakeTmp

    Run Build Command(s):/mingw64/bin/ninja.exe cmTC_4b2cb
    [1/2] Building C object CMakeFiles/cmTC_4b2cb.dir/testCCompiler.c.obj
    FAILED: CMakeFiles/cmTC_4b2cb.dir/testCCompiler.c.obj
    /mingw64/bin/cc.exe    -o CMakeFiles/cmTC_4b2cb.dir/testCCompiler.c.obj   -c testCCompiler.c
    CreateProcess failed: The system cannot find the file specified.
    ninja: build stopped: subcommand failed.

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:6 (project)

Error: --system-information failed on internal CMake!

meson.build:58:10: ERROR: Unable to find cmake

**Comment by smohantty** [comment]
@vtorri , That looks strange .. It passed both in CI as well as my windows machine.
Will disable the cmake generation for windows and only keep it for linux and mac

**Comment by smohantty** [comment]
@vtorri ,
Have pushed a patch to fix the issue #213 
Could you check if that fix your issue.

**Comment by vtorri** [comment]
CI is with visual studio (see .appveyor.yml). You should (must ?) add another OS for MSYS2. For example : 
https://project-renard.github.io/doc/development/meeting-log/posts/2016/05/03/windows-build-with-msys2/

you can search for other examples with msys2 + appveyor on internet

**Comment by vtorri** [comment]
it of course fixes the issue

**Comment by smohantty** [comment]
@vtorri ,
Regarding why we need cmake config files ..
   As far as i know the cmake projects use find_package to search for the library in the system. so without those config file projects build using cmake may fail to find rlotti in the system . 
Regarding CI for MSSYS2 . If you could raise a patch that would be great :)
