### ISSUE TITLE
Compilation broken with clang-8.0.0 (using meson)

### ISSUE THREAD

**Issue by msva** [Samsung/rlottie#217]
Hi there!
I faced broken compilation because of forced `-Werror` and the fact that clang throwing a `-Wdefaulted-function-deleted` warning:

```Shell
../rlottie-715c8450bf995f6a92fac1b64df77bd16effc7b0/src/vector/vbrush.h:41:5: error: explicitly defaulted default constructor is implicitly deleted [-Werror,-Wdefaulted-function-deleted]
    VGradient() = default;
    ^
../rlottie-715c8450bf995f6a92fac1b64df77bd16effc7b0/src/vector/vbrush.h:57:16: note: default constructor of 'VGradient' is implicitly deleted because variant field 'linear' has a non-trivial default constructor
        Linear linear;
               ^
1 error generated.
```

Well, adding `-Wno-error` to CXXFLAGS allows me to build the library, but since you forcing `-Werror`, I guess you'd like to know about such warning.

**Comment by smohantty** [comment]
@msva ,
Thanks for reporting . will reproduce it and push a patch for the same.

Thanks
Subhransu

**Comment by smohantty** [comment]
Have pushed a fix for the same.
#218
