### ISSUE TITLE
I can not understan,the function premulARGB in vglobal.h head file?

### ISSUE THREAD

**Issue by fantasyARM** [Samsung/rlottie#235]
uint premulARGB() const
    {
        int pr = (r * a) / 255;
        int pg = (g * a) / 255;
        int pb = (b * a) / 255;
        return uint((a << 24) | (pr << 16) | (pg << 8) | (pb));
    }
why the color(r,g,b) need to Multiply by proportion of alpha?

**Comment by hermet** [comment]
original premultiply of alpha equation is this,
rgb'  = rgb * (a / 255);
some of modern graphics systems are designed to pre-multiplied rgb value by alpha for composition,
https://en.wikipedia.org/wiki/Alpha_compositing

**Comment by fantasyARM** [comment]
ok,thanks at all.
