### ISSUE TITLE
Crash at v_ft_stroker:1785

### ISSUE THREAD

**Issue by overtake** [Samsung/rlottie#238]
Hi. This sticker cause a crash at 0 frame. can you check please?

[7351948.json.zip](https://github.com/Samsung/rlottie/files/3442813/7351948.json.zip)

**Comment by smohantty** [comment]
I have pushed a patch for the issue #239

**Comment by overtake** [comment]
Fixed. Thank you!

**Comment by overtake** [comment]
This

**Comment by smohantty** [comment]
@overtake ,
Yes it broke other resource in the example . I will investigate and push a proper fix .

**Comment by smohantty** [comment]
@overtake ,
I have pushed another patch to fix the regression #244 .
could you please test and confirm if your issue is resolved ?

**Comment by smohantty** [comment]
will close this issue as no reply received :)
