### ISSUE TITLE
Support Marker feature.

### ISSUE THREAD

**Issue by hermet** [Samsung/rlottie#280]
After Effect supports marker feature that specify timeline runinng paths. 
Apps can play a specific animation path from one lottie animation with this marker.

for instance,
If one animation has independent A(0.0 - 0.2)/B(0.2 - 0.7)/C(0.7 - 1) Animations in one lottie animation, apps could request each animation like this: 
play(A); play(B); play(C);

Currently bodymovin exports this marker properties, we need to check marker feature in after effect and how official Lottie supports this with its designed interfaces.

**Comment by hermet** [comment]
https://helpx.adobe.com/after-effects/using/layer-markers-composition-markers.html

**Comment by smohantty** [comment]
#281
