### ISSUE TITLE
image's opacity and  Gaussian blur

### ISSUE THREAD

**Issue by shudct** [Samsung/rlottie#286]
Our test json has image layers with opacity(not 100) or Gaussian blur, I wonder can rlottie render these effect or not. 

Below is our json and images. img_0.png has 10 transparency. img_11.png is gaussian blurred.
Thanks~
[test.zip](https://github.com/Samsung/rlottie/files/3712121/test.zip)

**Comment by smohantty** [comment]
@shudct ,

Have pushed a patch to support image with opacity #287 

We support both embedded image and external resource .

Please have a look at the supported AE feature by rlottie.
https://github.com/Samsung/rlottie#supported-after-effects-features

**Comment by shudct** [comment]
@smohantty thanks a lot!
Also, I find the render loop is slow, it costs nearly 8 sencond for 144 frames. I want to use openmp to accelerate the render speed, but the output is failed with black stripes and blurred screen. Can you give me some advice? Thanks again.

**Comment by smohantty** [comment]
@shudct ,
8seconds ? thats super slow . is it the same resource attached in test.zip ?
Our renderer is Software based . we try to speed up by generating outline in parallel.
If you share me the resource i can test and see if we can improve something in the library.

regarding openmp, we already run parallel jobs to process outline . but the rendering phase happens in one thread because of overlapping shapes. 
if i have access to the resource i can comment more on it.

**Comment by shudct** [comment]
@smohantty thank for your reply!
I have created another example API to save each frame(jpgs) rendered with 'stbi_write_jpg'. I test the speed by this API.  You can use the resource attached above(test.zip). If you have some other ways to speed the process, please share with me. Thanks again.

**Comment by smohantty** [comment]
@shudct ,
Any reason why you are saving them as JPEG files ?
If you want to render directly to the screen then rendering the buffer returned by rlottie directly will give you the best performance.

**Comment by shudct** [comment]
@smohantty 
The output generated by origin example API lottie2gif has some problems. It's blurred and has color distortion. So we generate each frames firstly, then we will use the jpgs for later operations, for example video or gif. I wonder if the process of each render is independent. If they are dependent, may be I know the reason of failure

**Comment by smohantty** [comment]
@shudct ,
Requesting a frame from Animation object is not thread safe. as it updates a shadow tree before rendering. so you cannot ask for a new frame for same Animation object simultaneously from other thread. If you want to speedup then you can create another Animation object with same resource and split the render task between 2 animation objects.
Ex: 
Animation* obj1 = loadfromFile("resource1.json");
Animation* obj2 = loadfromFile("resource1.json");
auto frameCount = obj1->totalFrame();

// render frames from 0 to frameCount/2 by obj1 and frameCount/2 to framecount frames by obj2 in parallel  .
This will reduce your render time by half.
