### ISSUE TITLE
Problem with generating frames through wasm

### ISSUE THREAD

**Issue by lyaskovec** [Samsung/rlottie#326]
Thanks for your library. 
But recently I faced one problem when used your rlottie library for generation frames through wasm.
`Uncaught RuntimeError: float unrepresentable in integer range`
You can also see this problem on http://rlottie.com/ 
I generated frames from a list from thousands of different files, but only the one caused such a problem
[file.zip](https://github.com/Samsung/rlottie/files/4255225/file.zip)

**Comment by smohantty** [comment]
@lyaskovec,
I checked the issue its only happening in the wasm build. am debugging the issue .
thanks for reporting.

**Comment by smohantty** [comment]
With latest wasm build this issue is not happening hence closing it.
