### ISSUE TITLE
can be used in javascript

### ISSUE THREAD

**Issue by songxx1990** [Samsung/rlottie#327]
hi：
is this package can be used in javascript?

**Comment by smohantty** [comment]
@songxx1990 ,
Yes you can build this library to wasm and can use it. As current browsers don't support Thread in wasm build the performance won't be same as native build.

For how to build for wasm you can check the https://github.com/rlottie/rlottie.github.io repo.

**Comment by songxx1990** [comment]
ok, thrank you;
