### ISSUE TITLE
render problem

### ISSUE THREAD

**Issue by shudct** [Samsung/rlottie#330]
I have tested some simple compositions as followed. But some strange problems have appeared.
1. when rendering shapes, it has black edges, however in AE file is not contained.
2. it seems that the shapes with opacity is not support?
3. when rendering images, especially the image moved or zoomed in/out, the texture is incoherently if you concat them to a video and has some color blocks.

hope for your reply! thanks~

[shape.aep.zip](https://github.com/Samsung/rlottie/files/4384765/shape.aep.zip)
[image aep.zip](https://github.com/Samsung/rlottie/files/4384767/image.aep.zip)
![截屏2020-03-26上午10 56 56](https://user-images.githubusercontent.com/11989304/77605716-8ead2480-6f50-11ea-80fb-5453eab1ea36.png)

**Comment by smohantty** [comment]
Hi,
Can you share the AEP with lower version . In my system i can't open it.

**Comment by shudct** [comment]
ok, I upload a new one.

[shape 副本 CC (15.x).aep.zip](https://github.com/Samsung/rlottie/files/4385134/shape.CC.15.x.aep.zip)
[image aep.zip](https://github.com/Samsung/rlottie/files/4385135/image.aep.zip)

**Comment by shudct** [comment]
hi, I wonder if any solution for the above problem or have you discover the reason.

**Comment by smohantty** [comment]
Hi @shudct ,
I tested the generated json file from the resource you have provided and tested it in http://rlottie.com/
as well as the generated GIF file using the sample application lottie2gif provided with source .
I don't see any problem with the white background .
![data json](https://user-images.githubusercontent.com/34466874/83985771-5b860900-a975-11ea-8f81-453c7ff916c0.gif)

As the layer above Red circle is not clipped to the circle boundary .. if the background is not white (maybe off white ) you can see those  borders . you can easily replicate that in rlottie.com by changing the background color.

Hope this helps

**Comment by shudct** [comment]
thanks again, I have found the problem.
By the way, I test the simple transforms, like shift and scale for images, the pixel of render result is a bit shaking and dismal.

![pos](https://user-images.githubusercontent.com/11989304/83997713-9433db80-a991-11ea-8978-f8e613018abf.gif)
![scale](https://user-images.githubusercontent.com/11989304/83997729-9d24ad00-a991-11ea-9834-ef8321a620f7.gif)
 the aep file is above.

Hope for your advice. Thanks again.

**Comment by smohantty** [comment]
@shudct , I can't open image.aep  because of the old AE . could you please attach the lower version AEP file.

**Comment by shudct** [comment]
[image 副本 CC (15.x).aep.zip](https://github.com/Samsung/rlottie/files/4749635/image.CC.15.x.aep.zip)

**Comment by smohantty** [comment]
Currently we are using simple liner interpolation for image resize thats why the scaling is not that smooth.
need to add Bilinear interpolation  for smooth scaling.

**Comment by shudct** [comment]
Thanks for your reply. By the way, could you tell me which script I can modify to achieve smooth scaling. Thanks again!

**Comment by hermet** [comment]
Created another issue ticket for bilinear interpolation support.
https://github.com/Samsung/rlottie/issues/346
