### ISSUE TITLE
compilation errors

### ISSUE THREAD

**Issue by vtorri** [Samsung/rlottie#332]
../example/lottieview.h:434:5: warning: no return statement in function returning non-void [-Wreturn-type]

this is a warning but with -Werror in meson build...

also : 

../example/lottieviewer.cpp:244:21: error: 'i' was not declared in this scope

**Comment by hermet** [comment]
commit 95bebc1ccbcf04e73aeefae4cea8c432b0a3749a (HEAD -> master, origin/master, origin/HEAD)
Author: Hermet Park <chuneon.park@samsung.com>
Date:   Mon Apr 6 16:46:44 2020 +0900

    example: return the value properly.

    this fixes a compile warning:

    warning: no return statement in function returning non-void [-Wreturn-type]

**Comment by vtorri** [comment]
and 

../example/lottieviewer.cpp:244:21: error: 'i' was not declared in this scope

it's about uint not recognize (uint32_T instead ?

????
