### ISSUE TITLE
compilation error in example

### ISSUE THREAD

**Issue by vtorri** [Samsung/rlottie#333]
../example/lottieviewer.cpp:244:21: error: 'i' was not declared in this scope

the type of i, uint,  is the problem : unknown type. Maybe use uint32_t instead ?

**Comment by hermet** [comment]
commit 50caa07e6d6a8394702d3ffd597680947e504671 (HEAD -> master, origin/master, origin/HEAD)
Author: Hermet Park <chuneon.park@samsung.com>
Date:   Wed Apr 8 15:56:56 2020 +0900

    use c++ standard type integer.

    vc++ doesn't recognize uint type?

**Comment by vtorri** [comment]
it's gcc on Windows which does not recognize it
