### ISSUE TITLE
make releases as xz archives

### ISSUE THREAD

**Issue by vtorri** [Samsung/rlottie#340]
hello

can you please make releases as xz archives ? it will reduce a lot the size of the tar balls

thank you

**Comment by smohantty** [comment]
@vtorri ,
I think the size is because of sample resource files in the example/resource folder.
The zip files are auto created by the github. 
Do you know if there is any option to generate xz file by github ?

Thanks
Subhransu

**Comment by hermet** [comment]
-rw-rw-r--  1 hermet hermet 3370201  6월 18 17:58 rlottie-0.1.tar.gz
-rw-rw-r--  1 hermet hermet 3040604  6월 18 17:58 rlottie-0.1.tar.xz
-rw-rw-r--  1 hermet hermet 3513297  6월 18 17:55 rlottie-0.1.zip

**Comment by hermet** [comment]
@vtorri  attached manually.

**Comment by vtorri** [comment]
thank you
