### ISSUE TITLE
Disable -werror for releases

### ISSUE THREAD

**Issue by juippis** [Samsung/rlottie#345]
Hey, 

I'd like to discuss disabling `-werror` flag for releases. I get the point of using it in development version, ie "git", but it may cause surprising issues when packaging tagged versions of rlottie. And especially in source-based distributions, with new glibc/gcc/clang releases. 

```patch
--- a/meson.build	2020-06-19 08:49:20.511888022 +0300
+++ b/meson.build	2020-06-19 08:49:49.166640657 +0300
@@ -1,6 +1,6 @@
 project('rlottie',
         'cpp',
-        default_options : ['warning_level=3', 'werror=true', 'cpp_std=c++14', 'optimization=s'],
+        default_options : ['cpp_std=c++14', 'optimization=s'],
         version : '0.1',
         license : 'LGPL-v2.1')

```

**Comment by smohantty** [comment]
makes sense .. I still want to werror enabled during developement . 
do i have to create a patch to disable it before every release and then reenable it ?

is there any better way to handle it ?

**Comment by hermet** [comment]
@smohantty we can disable them before tag the release version

**Comment by juippis** [comment]
I'm not aware of any elegant solution, although not doubting one exists... I'd either play with branches, or keep a copy of meson.build to swap between release -> development. Sorry :\

**Comment by smohantty** [comment]
@juippis ,
Have release v0.2 with werror off. so closing this .
