### ISSUE TITLE
Integrating with Godot Engine / License

### ISSUE THREAD

**Issue by fire** [Samsung/rlottie#353]
**Describe the project you are working on:**

Multiplayer game.

**Describe the problem or limitation you are having in your project:**

Want to play animated vector graphics.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

Adding telegram / Lottie animations to Godot Engine.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

Wanted to use rlottie, but LGPL is not compatible with MIT license. Godot Engine is a single executable so LGPL does not apply.

Need to get rlottie to output into a format where there's individual shapes / meshes and then transforms are applied on the group.

**Comment by hermet** [comment]
Do you need to embed rlottie lib in Godot Engine binary?
Otherwise You can keep MIT license with Godot Engine and LGPL with rlottie lib and link together.

**Comment by fire** [comment]
We cannot. The entire Godot Engine is a single executable.

**Comment by smohantty** [comment]
Hi,
We are thinking of changing the license to MIT license https://opensource.org/licenses/MIT
Will that enough for your use case ?

**Comment by fire** [comment]
That would be amazing!

**Comment by fire** [comment]
![2020-07-21 21-34-40](https://user-images.githubusercontent.com/32321/88134900-b167e680-cb9a-11ea-9f20-bd8e81f2ee3c.gif)

I did a trial run, but it's not compatible license wise and the next step is to handle bezier curves.

**Comment by smohantty** [comment]
@fire ,
You mean with the current LGPL license right ?
Regarding bezier curve .. is it related to rlottie ?

**Comment by fire** [comment]
I mean keep the artwork as vectorized as possible, rather than as a sprite for frame.

**Comment by fire** [comment]
Regarding the bezier curve, I mean keep everything as vectorized and as a series of https://github.com/Samsung/rlottie/blob/master/src/vector/vpath.h#L81 points. So it can be edited as animated and keep the small size of the original json.

**Comment by fire** [comment]
I copied your gif player demo. https://github.com/fire/lottie/blob/master/resource_importer_lottie.h#L111

**Comment by fire** [comment]
Regarding the license LGPL -> MIT, is there anything I can help, or is the process slow.

**Comment by smohantty** [comment]
@fire ,
There are few implementation we are using from LGPL based projects . we are replacing them with our own implementation or finding alternative based on MIT.

**Comment by fire** [comment]
Can you itemize the last remaining libraries? Maybe the search can be done by multiple people.

**Comment by hermet** [comment]
@fire @smohantty  https://github.com/Samsung/rlottie/commit/391434a1aa53d41be3f2f0de2363b3bcfe12533f

**Comment by hermet** [comment]
@smohantty  make it sure that all are satisfied with our result.
then I think you can release v0.2 with MIT license in the next week.

**Comment by fire** [comment]
Great! can't wait for https://github.com/Samsung/rlottie/blob/master/inc/rlottie.h sections to change from LGPL to MIT and the src folders.

Will await next week. 🎉
