### ISSUE TITLE
VBezier::tAtLength has an infinite loop.

### ISSUE THREAD

**Issue by fire** [Samsung/rlottie#389]
Tested using https://lottiefiles.com/27746-joypixels-partying-face-emoji-animation

Reverting to commit before https://github.com/Samsung/rlottie/commit/be4ec4f3d5a56a20373b22141c325156b39e38fb fixes.

**Comment by smohantty** [comment]
thanks for reporting the issue. Pushed a patch #390 to fix the issue. and also added the resource in the test suit.

**Comment by fire** [comment]
Fixes for me.
