### ISSUE TITLE
Create a rlottie debian package and submit to Debian 

### ISSUE THREAD

**Issue by smohantty** [Samsung/rlottie#39]

**Comment by smohantty** [comment]
Guide 
https://www.debian.org/doc/manuals/developers-reference/ch05.en.html

**Comment by smohantty** [comment]
https://blog.packagecloud.io/eng/2015/07/14/using-dh-make-to-prepare-debian-packages/
https://blog.packagecloud.io/eng/2015/05/18/building-deb-packages-with-pbuilder/

**Comment by smohantty** [comment]
https://www.debian.org/doc/manuals/maint-guide/first.en.html

**Comment by mymedia2** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=931832

**Comment by smohantty** [comment]
@mymedia2 ,
   Thanks for creating the bug report.
   Let me know if you need something from our side to expedite the process.
Subhransu

**Comment by smohantty** [comment]
@mymedia2 ,
Looks like you have some patches on top of rlottie for debian.
https://salsa.debian.org/mymedia-guest/rlottie/commit/7917ebf5ef4d8b4b67d7943ebbfba10b746654bd
If some of them can be applied in rlottie , it will be great if you contribute back to rlottie.
Thanks for the awesome work :)
