### ISSUE TITLE
rlottie renders only part of the file

### ISSUE THREAD

**Issue by nokeya** [Samsung/rlottie#407]
file: [https://lottiefiles.com/29056-nepenthe-illustration](https://lottiefiles.com/29056-nepenthe-illustration)

mac rlottie static debug, loadFromFile, renderSync

**expected result:**
as seen on the site

<img width="202" alt="image" src="https://user-images.githubusercontent.com/3000370/90161874-796c5180-dd9c-11ea-9db7-54a60acb66ee.png">

**observed result:**
<img width="146" alt="image" src="https://user-images.githubusercontent.com/3000370/90161685-28f4f400-dd9c-11ea-9070-884725b538a8.png">
(background is irrelevant, its from my app)

**Comment by smohantty** [comment]
@nokeya ,
This resource contains all layer as image layer.
As the image loader in rlottie is a module . am wondering if thats getting added to the library or not.
could you please build lottie by passing -DLOTTIE_MODULE=OFF and see if that helps.

NOTE: Still there is a bug in rlottie as the rendering is not same as the resource rendered by lottiefile.com

**Comment by smohantty** [comment]
added #408 patch to fix the above issue.
Please test and update the issue.

**Comment by nokeya** [comment]
#408 only = same result
#408 + `-DLOTTIE_MODULE=OFF` = success!
Thank you

<img width="208" alt="image" src="https://user-images.githubusercontent.com/3000370/90230628-803da780-de22-11ea-89b0-1dac835680f0.png">
