### ISSUE TITLE
Color red becomes purple on android

### ISSUE THREAD

**Issue by sonphan12** [Samsung/rlottie#433]
All rlottie frame's red color becomes purple. The issue happens only on newer versions of rlottie lib code. The older version on telegram works fine.

![image](https://user-images.githubusercontent.com/18615066/94240245-3aa1ed80-ff3d-11ea-9a39-743cd4cf4474.png)
Become 
![image](https://user-images.githubusercontent.com/18615066/94240281-47bedc80-ff3d-11ea-8cdd-f59b24abdb66.png)

**Comment by sonphan12** [comment]
Seems like new version of rlottie renders in BGRA bitmap format. I have to manual convert the bitmap to RGBA to render it on android since android's bitmap is RGBA.
This snippet of code make it work:
``` 
void convertToCanvasFormat()
    {
        int      totalBytes = mWidth * mHeight * 4;
        uint8_t *buffer = mBuffer.get();
        for (int i = 0; i < totalBytes; i += 4) {
            unsigned char a = buffer[i + 3];
            // compute only if alpha is non zero
            if (a) {
                unsigned char r = buffer[i + 2];
                unsigned char g = buffer[i + 1];
                unsigned char b = buffer[i];

                if (a != 255) {  // un premultiply
                    r = (r * 255) / a;
                    g = (g * 255) / a;
                    b = (b * 255) / a;

                    buffer[i] = r;
                    buffer[i + 1] = g;
                    buffer[i + 2] = b;

                } else {
                    // only swizzle r and b
                    buffer[i] = r;
                    buffer[i + 2] = b;
                }
            }
        }
    }

**Comment by smohantty** [comment]
@sonphan12 ,
rlottie always takes ARGB32_Premultiplied buffer , which means Alpha in the higher byte and Blue component in the lowest byte. 
I think Telegram has some local  patch to change the pixel format.
Thanks
Subhransu

**Comment by smohantty** [comment]
Please try your resource @ http://rlottie.com/ , if it shows different result then please file a issue.

**Comment by sonphan12** [comment]
> @sonphan12 ,
> rlottie always takes ARGB32_Premultiplied buffer , which means Alpha in the higher byte and Blue component in the lowest byte.
> I think Telegram has some local patch to change the pixel format.
> Thanks
> Subhransu

Thanks for the reply @smohantty . That's exactly what I found out, Alpha in the higher byte and Blue in the lowest byte means the format is BGRA. However Android's bit map is RGBA, so I need to use the mentioned above function to convert it.

**Comment by sonphan12** [comment]
> Please try your resource @ http://rlottie.com/ , if it shows different result then please file a issue.

I believe the wasm library which rlottie.com uses also relies on the above-mentioned function to work appropriately. Double-check may be needed.

**Comment by diamondhat** [comment]
IDK what's the problem, but I have this image as original, try to convert and still different result from online rlottie viewer. 

online viewer: 
![image](https://user-images.githubusercontent.com/68504048/95657180-de57d580-0ac7-11eb-9ee2-cadfffd3c91f.png)

original:
![image](https://user-images.githubusercontent.com/68504048/95657193-f0397880-0ac7-11eb-8c0a-6283a544b6fc.png)

converted: 
![image](https://user-images.githubusercontent.com/68504048/95657208-00515800-0ac8-11eb-91e2-077ee2fed1f8.png)


The question is how to convert image to RGBA? 

My conversion is: 
`for (int i = 0; i < total_bytes; ++i) // x * y
			{
				p_data[i] = p_data[i] << 8 | p_data[i] >> 24;
			}`

**Comment by sonphan12** [comment]
> IDK what's the problem, but I have this image as original, tried to convert and still have different result from online rlottie viewer.
> 
> OpenGL, Win64.
> 
> online viewer:
> ![image](https://user-images.githubusercontent.com/68504048/95657180-de57d580-0ac7-11eb-9ee2-cadfffd3c91f.png)
> 
> original:
> ![image](https://user-images.githubusercontent.com/68504048/95657193-f0397880-0ac7-11eb-8c0a-6283a544b6fc.png)
> 
> converted:
> ![image](https://user-images.githubusercontent.com/68504048/95657208-00515800-0ac8-11eb-91e2-077ee2fed1f8.png)
> 
> The question is how to convert image to RGBA?
> 
> My conversion is:
> // total_bytes = x * y
> for (int i = 0; i < total_bytes; ++i) {
> p_data[i] = p_data[i] << 8 | p_data[i] >> 24;
> }

Hi @diamondhat . Try using the function `convertToRGBABitmapFormat` in mine comment above to see if there is any differences. I’m using it in my project and it’s working great.

**Comment by diamondhat** [comment]
@sonphan12, your function 
![image](https://user-images.githubusercontent.com/68504048/95744347-01a98e80-0c48-11eb-87e6-60a28f44afa3.png)

**Comment by sonphan12** [comment]
> @sonphan12, your function
> ![image](https://user-images.githubusercontent.com/68504048/95744347-01a98e80-0c48-11eb-87e6-60a28f44afa3.png)

@diamondhat rlottie bitmap is **Premultiplied**. Please make sure your platform’s bitmap is Premultiplied, too.

**Comment by diamondhat** [comment]
@sonphan12, but I operate rendered buffer, no? 

p_lottie->renderSync(...); // Get lottie's bitmap??

**Comment by sonphan12** [comment]
> @sonphan12, but I operate rendered buffer, no?
> 
> p_lottie->renderSync(...); // Get lottie's bitmap??

Yes the buffer is itself the bitmap’s data.

**Comment by diamondhat** [comment]
@sonphan12 I don't get platform bitmap. I use OpenGL on windows 10.

**Comment by umerov1999** [comment]
Please add pixel format config to rlottie

**Comment by umerov1999** [comment]
> Seems like the new version of rlottie renders in BGRA bitmap format. I have to manually convert the bitmap to RGBA to render it on android since android's bitmap is RGBA.
> This snippet of code makes it work:
> 
> ```
> void convertToRGBABitmapFormat()
>     {
>         int      totalBytes = mWidth * mHeight * 4;
>         uint8_t *buffer = mBuffer.get();
>         for (int i = 0; i < totalBytes; i += 4) {
>             unsigned char a = buffer[i + 3];
>             // compute only if alpha is non zero
>             if (a) {
>                 unsigned char r = buffer[i + 2];
>                 unsigned char g = buffer[i + 1];
>                 unsigned char b = buffer[i];
> 
>                 if (a != 255) {  // un premultiply
>                     r = (r * 255) / a;
>                     g = (g * 255) / a;
>                     b = (b * 255) / a;
> 
>                     buffer[i] = r;
>                     buffer[i + 1] = g;
>                     buffer[i + 2] = b;
> 
>                 } else {
>                     // only swizzle r and b
>                     buffer[i] = r;
>                     buffer[i + 2] = b;
>                 }
>             }
>         }
>     }
> ```

void LottieParserImpl::getValue(model::Color &color)
{
    float val[4] = {0.f};
    int   i = 0;
    if (PeekType() == kArrayType) EnterArray();

    while (NextArrayValue()) {
        const auto value = GetDouble();
        if (i < 4) {
            val[i++] = value;
        }
    }

    if (mColorFilter) mColorFilter(val[0], val[1], val[2]);

    color.r = val[2];
    color.g = val[1];
    color.b = val[0];
}
