### ISSUE TITLE
freetype issue

### ISSUE THREAD

**Issue by umerov1999** [Samsung/rlottie#453]
in some animation in "v_ft_stroker.cpp. SW_FT_Error ft_stroke_border_cubicto - assert(border->start >= 0);"  border->start == -1. In telegram version rlottie work fine

**Comment by smohantty** [comment]
@umerov1999 
If you can attach a sample resource which reproduce the crash will be helpful.

**Comment by umerov1999** [comment]
This port to work in android [rlottie_android_0.2.tar.gz](https://github.com/Samsung/rlottie/files/5545931/rlottie_android_0.2.tar.gz)


anims, screens in https://drive.google.com/file/d/1V-jtdGaRry0kgxRGIGhpzPdm5J2aI-F1/view?usp=sharing

**Comment by umerov1999** [comment]
> @umerov1999
> If you can attach a sample resource which reproduce the crash will be helpful.

I attached my port for androod and animations

**Comment by umerov1999** [comment]
> @umerov1999
> If you can attach a sample resource which reproduce the crash will be helpful.

This manifests itself if several animations are loaded. If you are shipping successively, then everything is OK. Lottie_Cache off, Lottie Thread is also turned off

**Comment by umerov1999** [comment]
> @umerov1999
> If you can attach a sample resource which reproduce the crash will be helpful.

![Screenshot_20210219_215502](https://user-images.githubusercontent.com/3888404/108548698-454e8c00-72fd-11eb-9000-96f8ec45e8c8.png)
border->start is overflow

**Comment by umerov1999** [comment]
@smohantty
[vraster.cpp.txt](https://github.com/Samsung/rlottie/files/6013024/vraster.cpp.txt)
Fixed
