### ISSUE TITLE
Frames have a grey outline 

### ISSUE THREAD

**Issue by mgukov** [Samsung/rlottie#466]
All rendered frames have a gray outline at the border of the image and the transparent background. 
Is there a way to avoid this?

![image](https://user-images.githubusercontent.com/1714144/109043898-9b537300-76f3-11eb-96ec-94bc20807138.png)

**Comment by smohantty** [comment]
whats the file format you are using to store the rendered image, JPEG or PNG ?

I have test case which renders the resource using rlottie and saves them as PNG. I don't see any issue of grey border.

Reference test app
https://github.com/smohantty/ImageTest

**Comment by mgukov** [comment]
Thanks for reply, I was wrong, the problem was solved by the ARGBPremulToRGBA conversion.
