### ISSUE TITLE
MultiThread Error

### ISSUE THREAD

**Issue by umerov1999** [Samsung/rlottie#469]
Error Render Sync in multy thread

![image](https://user-images.githubusercontent.com/3888404/110812522-be0b8d00-8298-11eb-9de2-df05303ab62d.png)

Sample:
[1.json](https://github.com/Samsung/rlottie/files/6124129/1.json.txt)

#include <iostream>
#include <Windows.h>
#include "rlottie.h"
using namespace std;
using namespace rlottie;

DWORD WINAPI Th(LPVOID a) {
	std::unique_ptr<rlottie::Animation> anim;
	std::vector<uint32_t> buffer;
	size_t animWidth = 0, animHeight = 0;
	size_t bytesPerLine = 0;
	uint32_t curColor = 0;
	UINT curFrame = 0;
	anim = Animation::loadFromFile("1.json", false);
	anim->size(animWidth, animHeight);
	bytesPerLine = animWidth * sizeof(uint32_t);
	buffer.resize(bytesPerLine * animHeight);

	while (true) {
		if (curFrame > anim->totalFrame() - 1) {
			curFrame = 0;
		}
		else {
			curFrame++;
		}

			Surface surface = Surface(buffer.data(), animWidth, animHeight, bytesPerLine);
		anim->renderSync(curFrame, surface);
		for (int i = 0; i < animHeight; i++) {
			for (int j = 0; j < animWidth; ++j)
			{
				uint32_t* v = buffer.data() + i * animWidth + j;
				if (*v == 0) *v = curColor;
			}
		}
	}
	return 0;
}

int main()
{
	for (int i = 0; i < 20; i++) {
		CreateThread(NULL, NULL, &Th, NULL, NULL, 0);
	}
	system("pause");
}

**Comment by umerov1999** [comment]
But if i defined LOTTIE_THREAD_SUPPORT, works fine, no bugs

**Comment by smohantty** [comment]
@umerov1999 ,
Rlottie internally uses thread pool to generate rle from path data. by disabling the thread support rlottie uses single FT_Stroker instance to generate rle. in your usecase you are externally creating the threads and calling renderSync() which results in to multiple thread accessing same stroker instance hence the data race.

Is there any reason of not using render() api ? as it internally uses thread pool to do the rendering .

if you still want to use external thread , then just enable the LOTTIE_THREAD_SUPPORT, so that rle generation happens in thread pool which takes care of synchronization .

**Comment by umerov1999** [comment]
> @umerov1999 ,
> Rlottie internally uses thread pool to generate rle from path data. by disabling the thread support rlottie uses single FT_Stroker instance to generate rle. in your usecase you are externally creating the threads and calling renderSync() which results in to multiple thread accessing same stroker instance hence the data race.
> 
> Is there any reason of not using render() api ? as it internally uses thread pool to do the rendering .
> 
> if you still want to use external thread , then just enable the LOTTIE_THREAD_SUPPORT, so that rle generation happens in thread pool which takes care of synchronization .

I researched the telegram code of rlottie android, there threads were turned off.  I thought that maybe additional threads will affect the discharge of the battery.

**Comment by smohantty** [comment]
haven't done the energy consumption analysis . but mostly those threads will be idle (sleep state) . only during rendering they will be active. it won't be any worse than creating the threads externally.

Haven't checked the telegram code(could be old code) . are they using external threads to render lottie resource ? if they are using only one thread to render those resource that will work. but with multiple threads with thread support off , rlottie is not thread safe. 

even if we make it thread safe , the performance will be dropped significantly as multiple thread's have to synchronize for rle generation.

**Comment by umerov1999** [comment]
> haven't done the energy consumption analysis . but mostly those threads will be idle (sleep state) . only during rendering they will be active. it won't be any worse than creating the threads externally.
> 
> Haven't checked the telegram code(could be old code) . are they using external threads to render lottie resource ? if they are using only one thread to render those resource that will work. but with multiple threads with thread support off , rlottie is not thread safe.
> 
> even if we make it thread safe , the performance will be dropped significantly as multiple thread's have to synchronize for rle generation.

Yes, Telegram used thread in Java. Each Drawable has its own thread in pull. Thanks
![Screenshot_20210318-212511](https://user-images.githubusercontent.com/3888404/111677630-73f25080-8830-11eb-8869-4ec88630a62e.jpg)
