### ISSUE TITLE
Converting Lottie to 16 bit color for ESP32

### ISSUE THREAD

**Issue by tvanfossen** [Samsung/rlottie#494]
Hello,

I am attempting to run lottie animations on an ESP32 with a 240x320 LCD using LVGL.

Using the ESP-IDF, I've added LVGL v8 and lvgl_esp32_drivers to the project, and I'm using https://github.com/lvgl/lv_lib_rlottie to load lottie files. Custom PCBA with ST7789 display driver, whole bunch of tweaks to the ESP sdkconfig to get it to this point

Below is a 100x100 animation based upon https://lottiefiles.com/72599-loader. Two notable issues are image distortion and color distortion. Animation, though distorted, is quite stable in frame rate, and occupies only 2.3kb of memory! Image presents as elliptical instead of circular

![ezgif com-gif-maker](https://user-images.githubusercontent.com/17345424/129587277-95fd4c53-0db6-4d1b-bcfc-fd264d057738.gif)

Above gif is with color format set to TRUE_COLOR, image becomes further distorted if set to TRUE_COLOR_ALPHA

I believe the issue is related to trying to display ARGB32 when the display driver only supports 16 bit color. Are there any methods by which I could convert the lottie file to display as 16 bit color instead of 32?

Any help/suggestions would be much appreciated!

**Comment by tvanfossen** [comment]
![ezgif com-gif-maker(2)](https://user-images.githubusercontent.com/17345424/130621151-232051bd-4610-452a-a258-8d8cdbd9f216.gif)
![ezgif com-gif-maker(1)](https://user-images.githubusercontent.com/17345424/130621183-1e08e014-737b-4d66-b8e4-7865065220f0.gif)

100x75 animation based on https://lottiefiles.com/372-wifi-wiper (change to red/black color intended)
Latest, with 1st gif using TRUE_COLOR format, and 2nd with TRUE_COLOR_ALPHA with a color adjustment in place to convert from ARGB32 to RGB565 in LVGL

**Comment by tvanfossen-bissell** [comment]
![ezgif com-gif-maker(3)](https://user-images.githubusercontent.com/89472323/130671727-7bea4df4-80b9-4b5b-b1a3-ee82d377a5dd.gif)

Progress!! Looking like an actual animation

As most of the fixes I've been doing up to this point have been entirely in LVGL, going to close this issue - will continue commenting here https://github.com/lvgl/lv_lib_rlottie/issues/3

**Comment by ZakiuC** [comment]
Can I see your project please? I always get an error when I compile and link lottie.

**Comment by tvanfossen** [comment]
More documentation can be found [here](https://github.com/lvgl/lv_lib_rlottie/issues/3) as well as on LVGL's documentation for implementation on espressif chips.
