### ISSUE TITLE
librlottie-image-loader.so lacks SONAME 

### ISSUE THREAD

**Issue by juippis** [Samsung/rlottie#520]
`# objdump -p /usr/lib64/librlottie-image-loader.so | grep SONAME` returns nothing. 

`librlottie.so.0.2` is fine.

**Comment by mymedia2** [comment]
Image loader is a private library, that is not intended to directly use by third-party programs. So it need no SONAME.

**Comment by juippis** [comment]
Ah, not a "shared" library in that sense. Thanks for the explanation!
