### ISSUE TITLE
request an interface to get each layer's start / end frame data

### ISSUE THREAD

**Issue by hermet** [Samsung/rlottie#8]
The request scenario is, app and designers could make consensus that a special design, 

let's say it's "button"

And this resource may have 3 states: normal, focus in, focus out and the animation frame would be,
0 : normal
1 - 100 : focus in
101 - 200 : focus out

If specific layers could contain focus in, focus out animation frame, app doesn't need to hard code for these focus in/out animation implementation. They just read each layer's frame start/end and play those animation with them.

This is a example why they want layers' frame info. 
We could discuss whether we will support or not, how to support it.

**Comment by smohantty** [comment]
Looks like the same idea of embedding multiple animation in the same resource instead of giving individual resource.
Yes we can provide the api for the same .
I guess they only need the layer list of the composition layer to support this feature .
Anyway just check with them do they need all the layer's (layer can have child layer ) or only the 1st level children list .

**Comment by hermet** [comment]
Let's consider api point of view, 
My idea is we could provide an additional public class to manipulate or obtain internal attributes by "id"
ie,

class AttribAccessor
{
    AttribAccessor(Animation* animation);
    void frame(string& id, size_t* start, size_t end);       
};

The (potential) user may call like this,
attribAccessor->frame("focus_in", &start, &end);
attribAccessor->frame("focus_out", &start, &end);

This class could expand functions to access more attirbute such as color, geom, xxx by id.

**Comment by smohantty** [comment]
Well if Accessor takes the animation object , you still have to expose the api in animation class to be used by Acessor. if its not a friend class(in case of friend class case both will inter depend on each other).
So just adding the api in Animation class is much simpler approch.

**Comment by smohantty** [comment]
Did you check with the VD , if they need only 1st level children or the whole layer tree ? Is MinWoo Lee is working on the VD side ? I can ask him for the exact requirement.

**Comment by hermet** [comment]
@smohantty, 

As Animator class, it should be responsible for only animation behavior feature because it may need to support more property access, not only this layer frame.  If so, animator may have over methods for providing various property access. And the second reason is accessing properties is not the ordinary functions for normal usage. 

And About PropertyAccessor(as attribAccessor), it's just one example suggestion we can start to consider, since animator and PropertyAccessor both are wrapper interfaces, they would have actual bodies as internal private classes, they both could be friends to communicate.

The implementation is on you but you can consider my feedback, In the meantime, I think the property customizer as a coming feature, this request could be considered together.

**Comment by hermet** [comment]
@smohantty for layer question, you can contact to MinWoo Lee
